export const blockData = {
  blockA: {
    name: 'BLOCK A — ACADEMIC WING',
    color: '#4a9eff',
    desc: 'Main 8-floor academic building (9th & 10th under construction). Houses major departments, lecture halls, and labs.',
    floors: {
      'Basement': 'Tropical Café · Sports Room · Q Lab · 2-Wheeler Parking',
      'Ground': 'Lobby · Admissions · Registrar · Conference Rooms · HR · Provost · Exam Cell',
      '1st': 'University Office · Library · Raman Lab · DILO Room · Spectroscopy Lab · Research Labs',
      '2nd': 'Computer Labs A202-203 · Lecture Halls A204-209 · Server Room · Medical Room',
      '3rd': 'Physics Lab A316 · Chemistry Labs · Life Science Labs · Career Dev · Conf A304',
      '4th': 'Civil Labs A415-419 · Mechanical Labs · EEE Labs A402-406 · BMS Labs · Research Labs',
      '5th': 'Lecture Halls A-501/502 · Lab A-503 · Faculty Room',
      '6th': 'Lecture Halls A-601/602 · Lab A-603 · Faculty Room',
      '7th': 'Lecture Halls A-701 · Research Lab A-702',
      '8th': 'Lecture Hall A-801 · Research Lab A-802',
    },
    rooms: {
      'Basement': ['Tropical Café|amen', 'Sports Room|amen', 'Q-Lab (Student Space)|lab', '2-Wheeler Parking (A)|util', 'Car Parking|util'],
      'Ground': ['Lobby / Main Entry|adm', 'Guest Lounge A114|adm', 'Digital Tech A114|adm', 'Admissions A115|adm', 'Asst Registrar A116|adm', 'Accounts A117|adm', 'Exam Cell A119|adm', 'Exam Cell A120|adm', 'Registrar A121|adm', 'HR & First Aid A122|adm', 'Provost A123|adm', 'Conf Room A124|adm', 'Conf Room 2 A125|adm', 'NCC Office|adm'],
      '1st': ['University Office|adm', 'Conf Room 2 A125|adm', 'Lec Hall A107|lec', 'Lec Hall A108|lec', 'Lec Hall A109|lec', 'Faculty Room SOS|fac', 'Raman Lab|lab', 'Spectroscopy Lab|lab', 'DILO Room|amen', 'Research Lab SOS|lab', 'Library|amen'],
      '2nd': ['Faculty SBL A214|fac', 'Lec A215|lec', 'Lec A216|lec', 'Lec A217|lec', 'Medical Room A218|amen', 'Server Room A201|util', 'Comp Lab A202|lab', 'Comp Lab A202-B|lab', 'Comp Lab A203-A|lab', 'Comp Lab A203-B|lab', 'Lec Hall A204|lec', 'Faculty A205|fac', 'Lec Hall A206|lec', 'Comp Lab A207|lab', 'Lec Hall A208|lec', 'Lec A209|lec', 'Lec Hall A223|lec', 'Faculty A224|fac', 'Lec Hall A225|lec'],
      '3rd': ['Physics Lab A316|lab', 'Faculty SET A313|fac', 'Chem Lab A317|lab', 'Chem Instrum A318|lab', 'Life Sci Lab A311|lab', 'Career Dev A312|adm', 'Comp Lab A303|lab', 'Life Sci Lab A305|lab', 'Chem Lab A306|lab', 'Server A301|util', 'Faculty SET A307|fac', 'Chem Lab A310|lab', 'Cabin A302|fac', 'Conf Room A304|adm'],
      '4th': ['Civil Lab A418|lab', 'Civil Lab A419|lab', 'Civil Lab A415|lab', 'Mech Lab A414|lab', 'Research Chem A421|lab', 'Research Phy A422|lab', 'Comp Lab A416|lab', 'Research Civil A413|lab', 'Mech Lab A412|lab', 'Mech Eng Lab A411|lab', 'Mech Eng Lab A410|lab', 'EEE A402|lab', 'EEE A403|lab', 'EEE Lab A404|lab', 'EEE Lab A405|lab', 'EEE Lab A406|lab', 'BMS Lab 2 A407|lab', 'BMS Lab 1 A408|lab'],
      '5th': ['Lec Hall A-501|lec', 'Lec Hall A-502|lec', 'Lab A-503|lab', 'Faculty Room|fac'],
      '6th': ['Lec Hall A-601|lec', 'Lec Hall A-602|lec', 'Lab A-603|lab', 'Faculty Room|fac'],
      '7th': ['Lec Hall A-701|lec', 'Research Lab A-702|lab'],
      '8th': ['Lec Hall A-801|lec', 'Research Lab A-802|lab'],
    }
  },
  blockB: {
    name: 'BLOCK B — SEDA TOWER',
    color: '#ff6a44',
    desc: '6-floor SEDA block — School of Education & Developmental Arts. Tall red-accent tower at centre-front of campus.',
    floors: {
      'Basement': 'Workshop · Stationery Shop · Music Room · Parking',
      'Ground': 'Workshop Room · Store Room · Staff Restroom',
      '1st': 'SEDA Staff Room · Classroom B-101 · Classroom B-102',
      '2nd': 'Classroom B-201 · B-202 · B-203 · B-204',
      '3rd': 'Classroom B-301 · B-302 · B-303 · B-304',
      '4th': 'Classroom B-401 · B-402 · B-403 · B-404',
      '5th': 'B.Ed Classrooms · BAJMC Classrooms · SLSE Staff Room · SLSE Classrooms',
      '6th': 'Classroom B-601 · B-602 · B-603 · B-604 · Studio',
    },
    rooms: {
      'Basement': ['Workshop|lab', 'Stationery Shop|amen', 'Music Room|amen', 'Parking (Block B)|util'],
      'Ground': ['Workshop Room|lab', 'Store Room|util', 'Staff Restroom|util'],
      '1st': ['SEDA Staff Room|fac', 'Classroom B-101|lec', 'Classroom B-102|lec'],
      '2nd': ['Classroom B-201|lec', 'Classroom B-202|lec', 'Classroom B-203|lec', 'Classroom B-204|lec'],
      '3rd': ['Classroom B-301|lec', 'Classroom B-302|lec', 'Classroom B-303|lec', 'Classroom B-304|lec'],
      '4th': ['Classroom B-401|lec', 'Classroom B-402|lec', 'Classroom B-403|lec', 'Classroom B-404|lec'],
      '5th': ['B.Ed Classroom 1|lec', 'B.Ed Classroom 2|lec', 'BAJMC Classroom 1|lec', 'BAJMC Classroom 2|lec', 'SLSE Staff Room|fac', 'SLSE Classroom|lec'],
      '6th': ['Classroom B-601|lec', 'Classroom B-602|lec', 'Classroom B-603|lec', 'Classroom B-604|lec', 'Studio|amen'],
    }
  },
  blockC: {
    name: 'BLOCK C — ADMIN & CANTEEN',
    color: '#44cc88',
    desc: 'Left-side block housing canteen in basement and admissions office on ground floor. Connected to Block A.',
    floors: {
      'Basement': 'Canteen · Kitchen & Storage',
      'Ground': 'Admissions Office · Admin Block · Student Services',
    },
    rooms: {
      'Basement': ['Canteen|amen', 'Kitchen & Storage|util'],
      'Ground': ['Admissions Office|adm', 'Admin Block|adm', 'Student Services|adm'],
    }
  }
};

// --- CAMPUS GRAPH DATA ---
/**
 * NODES: These represent the "Vertices" of our graph.
 * Each node is a specific location on campus (room, stair, gate, etc.)
 * Properties:
 * - name: Display name
 * - type: Category (room, stair, gate, etc.)
 * - floor: Which floor it's on (B, G, 1, 2, etc.)
 * - block: Which building block it belongs to
 */
export const NODES = {
  gate1: { name: 'Gate 1', type: 'gate', floor: 'outside' },
  gate2: { name: 'Gate 2', type: 'gate', floor: 'outside' },
  parking: { name: 'Car Parking', type: 'outdoor', floor: 'outside' },
  basketball: { name: 'Basketball Court', type: 'outdoor', floor: 'outside' },
  pond: { name: 'Pond', type: 'outdoor', floor: 'outside' },
  amphi_g: { name: 'Amphitheatre (Ground)', type: 'amphi', floor: 'G' },
  amphi_b: { name: 'Amphitheatre (Basement)', type: 'amphi', floor: 'B' },
  c_admission: { name: 'Admission Cell', type: 'room', floor: 'G', block: 'blockC' },
  c_admin: { name: 'Admin Block', type: 'room', floor: 'G', block: 'blockC' },
  c_stair_g: { name: 'Block C Stair (G)', type: 'stair', floor: 'G', block: 'blockC' },
  c_canteen: { name: 'Canteen', type: 'room', floor: 'B', block: 'blockC' },
  c_kitchen: { name: 'Kitchen & Storage', type: 'room', floor: 'B', block: 'blockC' },
  c_stair_b: { name: 'Block C Stair (B)', type: 'stair', floor: 'B', block: 'blockC' },
  b_g_lobby: { name: 'Block B Lobby', type: 'room', floor: 'G', block: 'blockB' },
  b_g_workshop: { name: 'Workshop Room', type: 'room', floor: 'G', block: 'blockB' },
  b_stair_g: { name: 'Block B Stair (G)', type: 'stair', floor: 'G', block: 'blockB' },
  b_b_music: { name: 'Music Room', type: 'room', floor: 'B', block: 'blockB' },
  b_b_stationery: { name: 'Stationery Shop', type: 'room', floor: 'B', block: 'blockB' },
  b_b_parking: { name: 'Two-Wheeler Parking (B)', type: 'outdoor', floor: 'B', block: 'blockB' },
  b_stair_b: { name: 'Block B Stair (B)', type: 'stair', floor: 'B', block: 'blockB' },
  b_1st_1: { name: 'SEDA Staff Room', type: 'room', floor: '1', block: 'blockB' },
  b_1st_2: { name: 'Classroom B-101', type: 'room', floor: '1', block: 'blockB' },
  b_1st_3: { name: 'Classroom B-102', type: 'room', floor: '1', block: 'blockB' },
  b_stair_1: { name: 'Block B Stair (1F)', type: 'stair', floor: '1', block: 'blockB' },
  b_2nd_1: { name: 'Classroom B-201', type: 'room', floor: '2', block: 'blockB' },
  b_2nd_2: { name: 'Classroom B-202', type: 'room', floor: '2', block: 'blockB' },
  b_2nd_3: { name: 'Classroom B-203', type: 'room', floor: '2', block: 'blockB' },
  b_2nd_4: { name: 'Classroom B-204', type: 'room', floor: '2', block: 'blockB' },
  b_stair_2: { name: 'Block B Stair (2F)', type: 'stair', floor: '2', block: 'blockB' },
  b_3rd_1: { name: 'Classroom B-301', type: 'room', floor: '3', block: 'blockB' },
  b_3rd_2: { name: 'Classroom B-302', type: 'room', floor: '3', block: 'blockB' },
  b_3rd_3: { name: 'Classroom B-303', type: 'room', floor: '3', block: 'blockB' },
  b_3rd_4: { name: 'Classroom B-304', type: 'room', floor: '3', block: 'blockB' },
  b_stair_3: { name: 'Block B Stair (3F)', type: 'stair', floor: '3', block: 'blockB' },
  b_4th_1: { name: 'Classroom B-401', type: 'room', floor: '4', block: 'blockB' },
  b_4th_2: { name: 'Classroom B-402', type: 'room', floor: '4', block: 'blockB' },
  b_4th_3: { name: 'Classroom B-403', type: 'room', floor: '4', block: 'blockB' },
  b_4th_4: { name: 'Classroom B-404', type: 'room', floor: '4', block: 'blockB' },
  b_stair_4: { name: 'Block B Stair (4F)', type: 'stair', floor: '4', block: 'blockB' },
  b_5th_1: { name: 'B.Ed Classroom 1', type: 'room', floor: '5', block: 'blockB' },
  b_5th_2: { name: 'B.Ed Classroom 2', type: 'room', floor: '5', block: 'blockB' },
  b_5th_3: { name: 'BAJMC Classroom 1', type: 'room', floor: '5', block: 'blockB' },
  b_5th_4: { name: 'BAJMC Classroom 2', type: 'room', floor: '5', block: 'blockB' },
  b_5th_5: { name: 'SLSE Staff Room', type: 'room', floor: '5', block: 'blockB' },
  b_5th_6: { name: 'SLSE Classroom', type: 'room', floor: '5', block: 'blockB' },
  b_stair_5: { name: 'Block B Stair (5F)', type: 'stair', floor: '5', block: 'blockB' },
  b_6th_1: { name: 'Classroom B-601', type: 'room', floor: '6', block: 'blockB' },
  b_6th_2: { name: 'Classroom B-602', type: 'room', floor: '6', block: 'blockB' },
  b_6th_3: { name: 'Classroom B-603', type: 'room', floor: '6', block: 'blockB' },
  b_6th_4: { name: 'Classroom B-604', type: 'room', floor: '6', block: 'blockB' },
  b_6th_5: { name: 'Studio', type: 'room', floor: '6', block: 'blockB' },
  b_stair_6: { name: 'Block B Stair (6F)', type: 'stair', floor: '6', block: 'blockB' },
  a_b_cafe: { name: 'Tropical Cafe', type: 'room', floor: 'B', block: 'blockA' },
  a_b_sports: { name: 'Sports Room', type: 'room', floor: 'B', block: 'blockA' },
  a_b_qlab: { name: 'Q-Lab (Student Space)', type: 'room', floor: 'B', block: 'blockA' },
  a_b_parking: { name: 'Two-Wheeler Parking (A)', type: 'outdoor', floor: 'B', block: 'blockA' },
  a_stair_b: { name: 'Block A Stair (B)', type: 'stair', floor: 'B', block: 'blockA' },
  a_g_ncc: { name: 'NCC Office', type: 'room', floor: 'G', block: 'blockA' },
  a_g_lab: { name: 'Lab EEE & MECH', type: 'room', floor: 'G', block: 'blockA' },
  a_g_maggie: { name: 'Maggie & Coffee', type: 'room', floor: 'G', block: 'blockA' },
  a_g_sitting: { name: 'Sitting Area', type: 'room', floor: 'G', block: 'blockA' },
  a_g_library: { name: 'Library (G)', type: 'room', floor: 'G', block: 'blockA' },
  a_g_pond: { name: 'Pond Area', type: 'room', floor: 'G', block: 'blockA' },
  a_g_tea: { name: 'Tea Post', type: 'room', floor: 'G', block: 'blockA' },
  a_stair1_g: { name: 'Block A Stair 1 (G)', type: 'stair', floor: 'G', block: 'blockA' },
  a_stair2_g: { name: 'Block A Stair 2 (G)', type: 'stair', floor: 'G', block: 'blockA' },
  a_stair3_g: { name: 'Block A Stair 3 (G)', type: 'stair', floor: 'G', block: 'blockA' },
  a_1_office: { name: 'University Office', type: 'room', floor: '1', block: 'blockA' },
  a_1_conf2: { name: 'Conference Room 2', type: 'room', floor: '1', block: 'blockA' },
  a_1_raman: { name: 'Raman Lab', type: 'room', floor: '1', block: 'blockA' },
  a_1_spec: { name: 'Spectroscopy', type: 'room', floor: '1', block: 'blockA' },
  a_1_fac_sos: { name: 'Faculty SOS', type: 'room', floor: '1', block: 'blockA' },
  a_1_a110: { name: 'A110 Research Lab', type: 'room', floor: '1', block: 'blockA' },
  a_stair1_1: { name: 'Block A Stair 1 (1F)', type: 'stair', floor: '1', block: 'blockA' },
  a_stair2_1: { name: 'Block A Stair 2 (1F)', type: 'stair', floor: '1', block: 'blockA' },
  a_stair3_1: { name: 'Block A Stair 3 (1F)', type: 'stair', floor: '1', block: 'blockA' },
  a_2_fac_sbl: { name: 'A214 Faculty SBL', type: 'room', floor: '2', block: 'blockA' },
  a_2_208: { name: 'A208 Lec Hall', type: 'room', floor: '2', block: 'blockA' },
  a_2_207: { name: 'A207 Comp Lab', type: 'room', floor: '2', block: 'blockA' },
  a_2_223: { name: 'A223 Lec Hall', type: 'room', floor: '2', block: 'blockA' },
  a_2_225: { name: 'A225 Lec Hall', type: 'room', floor: '2', block: 'blockA' },
  a_2_201: { name: 'A201 Server', type: 'room', floor: '2', block: 'blockA' },
  a_2_202: { name: 'A202 Lab Comp', type: 'room', floor: '2', block: 'blockA' },
  a_2_206: { name: 'A206 Lec Hall', type: 'room', floor: '2', block: 'blockA' },
  a_stair1_2: { name: 'Block A Stair 1 (2F)', type: 'stair', floor: '2', block: 'blockA' },
  a_stair2_2: { name: 'Block A Stair 2 (2F)', type: 'stair', floor: '2', block: 'blockA' },
  a_stair3_2: { name: 'Block A Stair 3 (2F)', type: 'stair', floor: '2', block: 'blockA' },
  a_3_phy: { name: 'A316 Physics Lab', type: 'room', floor: '3', block: 'blockA' },
  a_3_fac: { name: 'A313 Faculty Room SET', type: 'room', floor: '3', block: 'blockA' },
  a_3_chem1: { name: 'A317 Chemistry Lab', type: 'room', floor: '3', block: 'blockA' },
  a_3_chem_inst: { name: 'A318 Chem Instrumentation', type: 'room', floor: '3', block: 'blockA' },
  a_3_career: { name: 'A312 Career Dev Cell', type: 'room', floor: '3', block: 'blockA' },
  a_3_lifesci: { name: 'A311 Life Science Lab', type: 'room', floor: '3', block: 'blockA' },
  a_3_comp: { name: 'A303 Comp Lab', type: 'room', floor: '3', block: 'blockA' },
  a_3_server: { name: 'A301 Server Room', type: 'room', floor: '3', block: 'blockA' },
  a_3_conf: { name: 'A304 Conference Room', type: 'room', floor: '3', block: 'blockA' },
  a_3_lifesci2: { name: 'A305 Life Science Lab', type: 'room', floor: '3', block: 'blockA' },
  a_3_chem2: { name: 'A306 Chemistry Lab', type: 'room', floor: '3', block: 'blockA' },
  a_3_fac2: { name: 'A307 Faculty Set Room', type: 'room', floor: '3', block: 'blockA' },
  a_3_chem3: { name: 'A310 Chemistry Lab', type: 'room', floor: '3', block: 'blockA' },
  a_stair1_3: { name: 'Block A Stair 1 (3F)', type: 'stair', floor: '3', block: 'blockA' },
  a_stair2_3: { name: 'Block A Stair 2 (3F)', type: 'stair', floor: '3', block: 'blockA' },
  a_stair3_3: { name: 'Block A Stair 3 (3F)', type: 'stair', floor: '3', block: 'blockA' },
  a_4_civil1: { name: 'A418 Civil Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_civil2: { name: 'A419 Civil Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_comp: { name: 'A416 Comp Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_civil3: { name: 'A415 Civil Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_mech1: { name: 'A414 Mech Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_res_chem: { name: 'A421 Research (Chem)', type: 'room', floor: '4', block: 'blockA' },
  a_4_res_phy: { name: 'A422 Research (Phy)', type: 'room', floor: '4', block: 'blockA' },
  a_4_res_civil: { name: 'A413 Research Lab (Civil)', type: 'room', floor: '4', block: 'blockA' },
  a_4_mech2: { name: 'A412 Mech Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_mech3: { name: 'A411 Mech Eng Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_mech4: { name: 'A410 Mech Eng Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_eee1: { name: 'A402 EEE Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_eee2: { name: 'A403 EEE Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_eee3: { name: 'A404 EEE Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_eee4: { name: 'A405 EEE Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_eee5: { name: 'A406 EEE Lab', type: 'room', floor: '4', block: 'blockA' },
  a_4_bms1: { name: 'A408 BMS Lab 1', type: 'room', floor: '4', block: 'blockA' },
  a_4_bms2: { name: 'A407 BMS Lab 2', type: 'room', floor: '4', block: 'blockA' },
  a_4_fac: { name: 'A409 Faculty Room', type: 'room', floor: '4', block: 'blockA' },
  a_stair1_4: { name: 'Block A Stair 1 (4F)', type: 'stair', floor: '4', block: 'blockA' },
  a_stair2_4: { name: 'Block A Stair 2 (4F)', type: 'stair', floor: '4', block: 'blockA' },
  a_stair3_4: { name: 'Block A Stair 3 (4F)', type: 'stair', floor: '4', block: 'blockA' },
  a_5_506: { name: 'Lecture Hall A-506', type: 'room', floor: '5', block: 'blockA' },
  a_5_507: { name: 'Lecture Hall A-507', type: 'room', floor: '5', block: 'blockA' },
  a_5_501: { name: 'Lecture Halls 501-505', type: 'room', floor: '5', block: 'blockA' },
  a_stair1_5: { name: 'Block A Stair 1 (5F)', type: 'stair', floor: '5', block: 'blockA' },
  a_stair2_5: { name: 'Block A Stair 2 (5F)', type: 'stair', floor: '5', block: 'blockA' },
  a_stair3_5: { name: 'Block A Stair 3 (5F)', type: 'stair', floor: '5', block: 'blockA' },
  a_6_staff: { name: 'Faculty Room (6F)', type: 'room', floor: '6', block: 'blockA' },
  a_6_601: { name: 'Lecture Hall A-601', type: 'room', floor: '6', block: 'blockA' },
  a_6_602: { name: 'Lecture Hall A-602', type: 'room', floor: '6', block: 'blockA' },
  a_6_603: { name: 'Lecture Hall A-603', type: 'room', floor: '6', block: 'blockA' },
  a_6_604: { name: 'Lecture Hall A-604', type: 'room', floor: '6', block: 'blockA' },
  a_6_605: { name: 'Lecture Hall A-605', type: 'room', floor: '6', block: 'blockA' },
  a_stair1_6: { name: 'Block A Stair 1 (6F)', type: 'stair', floor: '6', block: 'blockA' },
  a_stair2_6: { name: 'Block A Stair 2 (6F)', type: 'stair', floor: '6', block: 'blockA' },
  a_stair3_6: { name: 'Block A Stair 3 (6F)', type: 'stair', floor: '6', block: 'blockA' },
  a_7_staff: { name: 'Faculty Room (7F)', type: 'room', floor: '7', block: 'blockA' },
  a_7_server: { name: 'Server Room (7F)', type: 'room', floor: '7', block: 'blockA' },
  a_7_701: { name: 'Lecture Hall A-701', type: 'room', floor: '7', block: 'blockA' },
  a_7_702: { name: 'Lecture Hall A-702', type: 'room', floor: '7', block: 'blockA' },
  a_7_703: { name: 'Lecture Hall A-703', type: 'room', floor: '7', block: 'blockA' },
  a_7_704: { name: 'Lecture Hall A-704', type: 'room', floor: '7', block: 'blockA' },
  a_7_705: { name: 'Lecture Hall A-705', type: 'room', floor: '7', block: 'blockA' },
  a_stair1_7: { name: 'Block A Stair 1 (7F)', type: 'stair', floor: '7', block: 'blockA' },
  a_stair2_7: { name: 'Block A Stair 2 (7F)', type: 'stair', floor: '7', block: 'blockA' },
  a_stair3_7: { name: 'Block A Stair 3 (7F)', type: 'stair', floor: '7', block: 'blockA' },
  a_8_tinker: { name: 'Tinkerer\'s Lab', type: 'room', floor: '8', block: 'blockA' },
  a_8_psych: { name: 'Psychology Lab', type: 'room', floor: '8', block: 'blockA' },
  a_8_counsel: { name: 'Counselling (809)', type: 'room', floor: '8', block: 'blockA' },
  a_8_nif: { name: 'NIF', type: 'room', floor: '8', block: 'blockA' },
  a_8_801: { name: 'Lecture Hall A-801', type: 'room', floor: '8', block: 'blockA' },
  a_8_802: { name: 'Lecture Hall A-802', type: 'room', floor: '8', block: 'blockA' },
  a_8_803: { name: 'Lecture Hall A-803', type: 'room', floor: '8', block: 'blockA' },
  a_8_804: { name: 'Lecture Hall A-804', type: 'room', floor: '8', block: 'blockA' },
  a_8_805: { name: 'Lecture Hall A-805', type: 'room', floor: '8', block: 'blockA' },
  a_stair1_8: { name: 'Block A Stair 1 (8F)', type: 'stair', floor: '8', block: 'blockA' },
  a_stair2_8: { name: 'Block A Stair 2 (8F)', type: 'stair', floor: '8', block: 'blockA' },
  a_stair3_8: { name: 'Block A Stair 3 (8F)', type: 'stair', floor: '8', block: 'blockA' },
};

/**
 * EDGES: These represent the "Weighted Connections" between nodes.
 * Each entry is an array: [NodeA, NodeB, Distance]
 * - NodeA & NodeB: The two locations that are connected.
 * - Distance: The "weight" or cost to travel between them.
 * 
 * Dijkstra's algorithm uses these weights to find the path with the 
 * lowest total sum of distances.
 */
export const EDGES = [
  ['gate1', 'c_admission', 30], ['gate1', 'amphi_g', 50],
  ['gate2', 'c_admission', 25], ['gate2', 'amphi_g', 55], ['gate2', 'parking', 40],
  ['parking', 'b_g_lobby', 20],
  ['c_admission', 'amphi_g', 30], ['c_admission', 'b_g_lobby', 35], ['c_admission', 'c_admin', 10], ['c_admission', 'c_stair_g', 15],
  ['c_canteen', 'amphi_b', 20], ['c_canteen', 'c_kitchen', 10], ['c_canteen', 'c_stair_b', 15],
  ['c_stair_b', 'c_stair_g', 20],
  ['amphi_g', 'amphi_b', 15], ['amphi_g', 'b_g_lobby', 25], ['amphi_g', 'a_stair3_g', 35],
  ['amphi_b', 'a_b_cafe', 20], ['amphi_b', 'b_b_music', 20],
  ['a_g_ncc', 'a_stair3_g', 30], ['a_g_lab', 'a_stair3_g', 10], ['a_g_maggie', 'a_stair3_g', 15], ['a_g_sitting', 'a_stair3_g', 20],
  ['a_g_library', 'a_stair1_g', 25], ['a_g_pond', 'a_stair1_g', 30], ['a_g_tea', 'a_stair3_g', 35],
  ['a_stair1_g', 'pond', 30], ['pond', 'b_g_lobby', 30], ['pond', 'basketball', 25],
  ['basketball', 'a_stair1_g', 20],
  ['a_stair_b', 'a_b_cafe', 15], ['a_b_cafe', 'a_b_sports', 20],
  ['a_b_sports', 'a_b_qlab', 20], ['a_b_qlab', 'a_b_parking', 30],
  ['a_stair1_g', 'a_stair_b', 20], ['a_stair2_g', 'a_stair_b', 25], ['a_stair3_g', 'a_stair_b', 30],
  ['a_stair1_g', 'a_stair1_1', 20], ['a_stair1_1', 'a_stair1_2', 20], ['a_stair1_2', 'a_stair1_3', 20],
  ['a_stair1_3', 'a_stair1_4', 20], ['a_stair1_4', 'a_stair1_5', 20], ['a_stair1_5', 'a_stair1_6', 20],
  ['a_stair1_6', 'a_stair1_7', 20], ['a_stair1_7', 'a_stair1_8', 20],
  ['a_stair2_g', 'a_stair2_1', 20], ['a_stair2_1', 'a_stair2_2', 20], ['a_stair2_2', 'a_stair2_3', 20],
  ['a_stair2_3', 'a_stair2_4', 20], ['a_stair2_4', 'a_stair2_5', 20], ['a_stair2_5', 'a_stair2_6', 20],
  ['a_stair2_6', 'a_stair2_7', 20], ['a_stair2_7', 'a_stair2_8', 20],
  ['a_stair3_g', 'a_stair3_1', 20], ['a_stair3_1', 'a_stair3_2', 20], ['a_stair3_2', 'a_stair3_3', 20],
  ['a_stair3_3', 'a_stair3_4', 20], ['a_stair3_4', 'a_stair3_5', 20], ['a_stair3_5', 'a_stair3_6', 20],
  ['a_stair3_6', 'a_stair3_7', 20], ['a_stair3_7', 'a_stair3_8', 20],
  ['a_stair1_1', 'a_1_office', 15], ['a_stair2_1', 'a_1_raman', 15],
  ['a_stair3_1', 'a_1_conf2', 15], ['a_stair3_1', 'a_1_spec', 20],
  ['a_1_office', 'a_1_raman', 20], ['a_1_raman', 'a_1_spec', 15],
  ['a_1_fac_sos', 'a_stair2_1', 10], ['a_1_a110', 'a_stair3_1', 12],
  ['a_stair1_2', 'a_2_201', 10], ['a_stair2_2', 'a_2_202', 15],
  ['a_stair3_2', 'a_2_208', 15], ['a_2_201', 'a_2_202', 15], ['a_2_202', 'a_2_208', 20],
  ['a_2_fac_sbl', 'a_stair1_2', 12], ['a_2_207', 'a_stair3_2', 10], ['a_2_223', 'a_stair3_2', 12], ['a_2_225', 'a_stair3_2', 14], ['a_2_206', 'a_stair3_2', 16],
  ['a_stair1_3', 'a_3_phy', 15], ['a_stair2_3', 'a_3_chem1', 15], ['a_stair3_3', 'a_3_lifesci', 15],
  ['a_3_phy', 'a_3_chem1', 20], ['a_3_chem1', 'a_3_lifesci', 20],
  ['a_3_fac', 'a_stair1_3', 10], ['a_3_chem_inst', 'a_stair2_3', 12], ['a_3_career', 'a_stair3_3', 10],
  ['a_3_comp', 'a_stair2_3', 10], ['a_3_server', 'a_stair2_3', 12], ['a_3_conf', 'a_stair2_3', 14],
  ['a_3_lifesci2', 'a_stair2_3', 16], ['a_3_chem2', 'a_stair2_3', 18], ['a_3_fac2', 'a_stair2_3', 20], ['a_3_chem3', 'a_stair2_3', 22],
  ['a_stair1_4', 'a_4_civil1', 15], ['a_stair2_4', 'a_4_mech1', 15], ['a_stair3_4', 'a_4_eee1', 15],
  ['a_4_civil1', 'a_4_mech1', 20], ['a_4_mech1', 'a_4_eee1', 20],
  ['a_4_civil2', 'a_4_civil1', 10], ['a_4_comp', 'a_4_civil1', 12], ['a_4_civil3', 'a_4_civil2', 10],
  ['a_4_res_chem', 'a_stair2_4', 10], ['a_4_res_phy', 'a_stair2_4', 12], ['a_4_res_civil', 'a_stair2_4', 14],
  ['a_4_mech2', 'a_stair2_4', 16], ['a_4_mech3', 'a_stair2_4', 18], ['a_4_mech4', 'a_stair2_4', 20],
  ['a_4_eee2', 'a_4_eee1', 5], ['a_4_eee3', 'a_4_eee2', 5], ['a_4_eee4', 'a_4_eee3', 5], ['a_4_eee5', 'a_4_eee4', 5],
  ['a_4_bms1', 'a_4_eee1', 10], ['a_4_bms2', 'a_4_eee1', 12], ['a_4_fac', 'a_4_eee1', 14],
  ['a_stair1_5', 'a_5_501', 15], ['a_stair2_5', 'a_5_501', 20], ['a_stair3_5', 'a_5_506', 15],
  ['a_5_506', 'a_5_507', 10], ['a_5_501', 'a_5_507', 25],
  ['a_stair1_6', 'a_6_601', 15], ['a_stair2_6', 'a_6_605', 15], ['a_6_601', 'a_6_602', 10], ['a_6_602', 'a_6_605', 20],
  ['a_6_staff', 'a_stair1_6', 10], ['a_6_603', 'a_stair2_6', 12], ['a_6_604', 'a_stair2_6', 14],
  ['a_stair1_7', 'a_7_701', 15], ['a_stair2_7', 'a_7_705', 15], ['a_7_701', 'a_7_705', 25],
  ['a_7_staff', 'a_stair1_7', 10], ['a_7_server', 'a_stair2_7', 12], ['a_7_702', 'a_stair2_7', 14], ['a_7_703', 'a_stair2_7', 16], ['a_7_704', 'a_stair2_7', 18],
  ['a_stair1_8', 'a_8_801', 15], ['a_stair2_8', 'a_8_805', 15], ['a_8_801', 'a_8_psych', 20], ['a_8_psych', 'a_8_counsel', 15],
  ['a_8_tinker', 'a_stair1_8', 10], ['a_8_counsel', 'a_stair1_8', 12], ['a_8_nif', 'a_stair1_8', 14],
  ['a_8_802', 'a_stair2_8', 10], ['a_8_803', 'a_stair2_8', 12], ['a_8_804', 'a_stair2_8', 14],
  ['b_stair_b', 'b_stair_g', 20], ['b_stair_g', 'b_stair_1', 20], ['b_stair_1', 'b_stair_2', 20],
  ['b_stair_2', 'b_stair_3', 20], ['b_stair_3', 'b_stair_4', 20], ['b_stair_4', 'b_stair_5', 20], ['b_stair_5', 'b_stair_6', 20],
  ['b_stair_b', 'b_b_music', 15], ['b_b_music', 'b_b_stationery', 15], ['b_b_stationery', 'b_b_parking', 20],
  ['b_stair_g', 'b_g_lobby', 10], ['b_g_lobby', 'b_g_workshop', 15],
  ['b_stair_1', 'b_1st_1', 10], ['b_1st_1', 'b_1st_2', 10], ['b_1st_2', 'b_1st_3', 10],
  ['b_stair_2', 'b_2nd_1', 10], ['b_2nd_1', 'b_2nd_2', 10], ['b_2nd_2', 'b_2nd_3', 10], ['b_2nd_3', 'b_2nd_4', 10],
  ['b_stair_3', 'b_3rd_1', 10], ['b_3rd_1', 'b_3rd_2', 10], ['b_3rd_2', 'b_3rd_3', 10], ['b_3rd_3', 'b_3rd_4', 10],
  ['b_stair_4', 'b_4th_1', 10], ['b_4th_1', 'b_4th_2', 10], ['b_4th_2', 'b_4th_3', 10], ['b_4th_3', 'b_4th_4', 10],
  ['b_stair_5', 'b_5th_1', 10], ['b_5th_1', 'b_5th_2', 10], ['b_5th_2', 'b_5th_3', 10], ['b_5th_3', 'b_5th_4', 10], ['b_5th_4', 'b_5th_5', 10], ['b_5th_5', 'b_5th_6', 10],
  ['b_stair_6', 'b_6th_1', 10], ['b_6th_1', 'b_6th_2', 10], ['b_6th_2', 'b_6th_3', 10], ['b_6th_3', 'b_6th_4', 10], ['b_6th_4', 'b_6th_5', 10],
];
